import { isTS } from '../utils/lang.js';

/**
 * DockerEmitter — Dockerfile, docker-compose.yml (app + datastores), and
 * an ecosystem.config.js for PM2 cluster deploys.
 */
export function emitDockerFiles(analysis, language = 'javascript') {
  return {
    Dockerfile: dockerfile(language),
    '.dockerignore': dockerignore(),
    'docker-compose.yml': dockerCompose(analysis),
    'ecosystem.config.js': ecosystemConfig(language),
  };
}

function dockerfile(language) {
  const ts = isTS(language);
  if (!ts) {
    return `# ── Build stage ──────────────────────────────────────────
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

# ── Runtime stage ────────────────────────────────────────
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
USER node
CMD ["node", "src/server.js"]
`;
  }

  return `# ── Build stage ──────────────────────────────────────────
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm ci
COPY src ./src
RUN npm run build

# ── Runtime stage ────────────────────────────────────────
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
USER node
CMD ["node", "dist/server.js"]
`;
}

function dockerignore() {
  return `node_modules\nnpm-debug.log\n.env\n.git\ncoverage\ndist\n`;
}

function dockerCompose(analysis) {
  const { stats, dbNodes, cacheNodes } = analysis;
  const services = [];

  services.push(`  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
${stats.dbCount > 0 ? (stats.isPostgres
      ? `      DATABASE_URL: postgresql://admin:secret@postgres:5432/app\n`
      : `      MONGODB_URI: mongodb://mongo:27017/app\n`) : ''}${stats.hasCaching ? `      REDIS_URL: redis://redis:6379\n` : ''}    depends_on:
${dbNodes.length > 0 ? `      - ${stats.isPostgres ? 'postgres' : 'mongo'}\n` : ''}${cacheNodes.length > 0 ? '      - redis\n' : ''}    restart: unless-stopped
`);

  if (dbNodes.length > 0) {
    services.push(stats.isPostgres ? `  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
` : `  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
`);
  }

  if (cacheNodes.length > 0) {
    services.push(`  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
`);
  }

  const volumeNames = [
    dbNodes.length > 0 ? (stats.isPostgres ? 'postgres_data' : 'mongo_data') : null,
    cacheNodes.length > 0 ? 'redis_data' : null,
  ].filter(Boolean);

  return `# docker-compose.yml — Generated by Architect.io
services:
${services.join('\n')}
${volumeNames.length > 0 ? `volumes:\n${volumeNames.map((v) => `  ${v}:`).join('\n')}\n` : ''}`;
}

function ecosystemConfig(language) {
  const ts = isTS(language);
  return `module.exports = {
  apps: [
    {
      name: 'architect-io-generated',
      script: '${ts ? './dist/server.js' : './src/server.js'}',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      max_memory_restart: '512M',
    },
  ],
};
`;
}
