import { toCamelCase, toKebabCase } from '../utils/naming.js';
import { hasPasswordField } from '../utils/fieldHeuristics.js';
import { fileExt, isTS } from '../utils/lang.js';

/**
 * ServerEmitter — package.json, src/server.js bootstrap, and the small
 * set of project-root config files (.env.example, .eslintrc, .prettierrc).
 * Everything here is infrastructure that doesn't belong to any one entity.
 */
export function emitServerFiles(analysis, apiEntities, projectConfig = {}) {
  const ext = fileExt(projectConfig.language);
  return {
    'package.json': packageJsonFile(analysis, projectConfig),
    [`src/server.${ext}`]: serverFile(analysis, apiEntities, projectConfig),
    '.env.example': envExampleFile(analysis),
    '.eslintrc.json': eslintFile(projectConfig),
    '.prettierrc': prettierFile(),
    '.gitignore': gitignoreFile(),
  };
}

function packageJsonFile(analysis, projectConfig) {
  const { stats } = analysis;
  const ts = isTS(projectConfig.language);
  const deps = {
    express: '^4.18.2',
    dotenv: '^16.0.3',
    cors: '^2.8.5',
    helmet: '^7.1.0',
  };
  if (projectConfig.validation === 'joi') deps.joi = '^17.13.3';
  else deps.zod = '^3.23.8';
  const withDocs = projectConfig.docs !== 'none';
  if (withDocs) deps['swagger-ui-express'] = '^5.0.1';

  if (stats.dbCount > 0 && stats.isMongo) deps.mongoose = '^8.0.0';
  if (stats.dbCount > 0 && stats.isPostgres) deps.pg = '^8.11.0';
  if (stats.hasCaching) deps.ioredis = '^5.3.2';
  const usesAuth = stats.hasAuth || analysis.apiNodes.some((n) => n.data?.authEnabled);
  if (usesAuth) deps.jsonwebtoken = '^9.0.0';
  const needsBcrypt = usesAuth || analysis.entities.some((e) => hasPasswordField(e.data?.fields || []));
  if (needsBcrypt) deps.bcryptjs = '^2.4.3';
  if (analysis.middlewareNodes.some((n) => n.data?.middlewareType === 'Rate Limiter')) {
    deps['express-rate-limit'] = '^7.4.0';
  }
  if (stats.hasMessaging) deps.amqplib = '^0.10.3';

  const devDeps = {
    nodemon: '^3.0.0',
    jest: '^29.0.0',
    supertest: '^7.0.0',
    eslint: '^8.57.0',
    prettier: '^3.3.0',
  };
  if (stats.dbCount > 0 && stats.isMongo) devDeps['mongodb-memory-server'] = '^10.0.0';

  const scripts = {
    start: ts ? 'node dist/server.js' : 'node src/server.js',
    dev: ts ? 'tsx watch src/server.ts' : 'nodemon src/server.js',
    test: 'node --experimental-vm-modules node_modules/.bin/jest',
    'test:coverage': 'node --experimental-vm-modules node_modules/.bin/jest --coverage',
    lint: 'eslint src',
    'lint:fix': 'eslint src --fix',
  };

  if (ts) {
    scripts.build = 'tsc';
    devDeps.typescript = '^5.5.4';
    devDeps.tsx = '^4.16.5';
    devDeps['@types/node'] = '^20.14.0';
    devDeps['@types/express'] = '^4.17.21';
    devDeps['@types/cors'] = '^2.8.17';
    devDeps['ts-jest'] = '^29.2.4';
    devDeps['@types/jest'] = '^29.5.12';
    devDeps['@types/supertest'] = '^6.0.2';
    devDeps['@typescript-eslint/parser'] = '^7.18.0';
    devDeps['@typescript-eslint/eslint-plugin'] = '^7.18.0';
    if (deps.jsonwebtoken) devDeps['@types/jsonwebtoken'] = '^9.0.6';
    if (deps.bcryptjs) devDeps['@types/bcryptjs'] = '^2.4.6';
    if (withDocs) devDeps['@types/swagger-ui-express'] = '^4.1.6';
    if (deps.pg) devDeps['@types/pg'] = '^8.11.6';
  }

  return JSON.stringify({
    name: 'architect-io-generated',
    version: '1.0.0',
    description: `Generated by Architect.io — ${stats.totalNodes} nodes, ${stats.totalEdges} connections`,
    main: ts ? 'dist/server.js' : 'src/server.js',
    type: 'module',
    scripts,
    dependencies: deps,
    devDependencies: devDeps,
  }, null, 2);
}

function serverFile(analysis, apiEntities, projectConfig) {
  const { stats } = analysis;
  const ts = isTS(projectConfig.language);
  const apiPrefix = projectConfig.apiVersioning === false ? '/api' : '/api/v1';
  const withDocs = projectConfig.docs !== 'none';

  const imports = apiEntities.map((s) => {
    const name = toCamelCase(s.data?.name || s.id);
    const path = toKebabCase(s.data?.name || s.id);
    return `import ${name}Router from './modules/${path}/${path}.routes.js';`;
  }).join('\n');

  const routeRegistrations = apiEntities.map((s) => {
    const name = toCamelCase(s.data?.name || s.id);
    const path = toKebabCase(s.data?.name || s.id);
    return `app.use('${apiPrefix}/${path}', ${name}Router);`;
  }).join('\n');

  return `/**
 * server.js — Generated by Architect.io
 * Architecture: ${stats.totalNodes} nodes, ${stats.totalEdges} connections
 * Modules: ${apiEntities.length} | Databases: ${stats.dbCount}
 */
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
${withDocs ? "import swaggerUi from 'swagger-ui-express';\n" : ''}import { config } from './config/index.js';
${stats.dbCount > 0 ? `import { connectDatabase, disconnectDatabase } from './config/database.js';` : ''}
${stats.hasCaching ? `import { connectRedis, disconnectRedis } from './config/redis.js';` : ''}
import { logger } from './core/logger.js';
import { requestId } from './core/requestId.js';
import { requestLogger } from './middleware/requestLogger.js';
import { errorHandler } from './middleware/errorHandler.js';
import { notFound } from './middleware/notFound.js';
${withDocs ? `import { swaggerDocument } from './config/swagger.js';\n` : ''}${imports}

const app = express();

// ── Security & Parsing Middleware ──
app.use(helmet());
app.use(cors({ origin: config.corsOrigin, credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(requestId);
app.use(requestLogger);
${withDocs ? `
// ── API Docs ──
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
` : ''}
// ── Health Check ──
app.get('/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString(), uptime: process.uptime() });
});

// ── API Routes ──
${routeRegistrations}

// ── 404 + Error Handling ──
app.use(notFound);
app.use(errorHandler);

// ── Bootstrap ──
let server${ts ? ': ReturnType<typeof app.listen> | undefined' : ''};

async function bootstrap()${ts ? ': Promise<void>' : ''} {
  try {
    ${stats.dbCount > 0 ? 'await connectDatabase();' : ''}
    ${stats.hasCaching ? 'connectRedis();' : ''}
    server = app.listen(config.port, () => {
      logger.info(\`Server running on http://localhost:\${config.port}\`);
      logger.info(\`Architecture: ${apiEntities.length} modules, ${stats.dbCount} data stores\`);
    });
  } catch (error) {
    logger.error('Failed to start server', error);
    process.exit(1);
  }
}

// ── Graceful Shutdown ──
async function shutdown(signal${ts ? ': string' : ''})${ts ? ': Promise<void>' : ''} {
  logger.info(\`\${signal} received. Starting graceful shutdown...\`);

  server?.close(async () => {
    logger.info('HTTP server closed');
    ${stats.dbCount > 0 ? 'await disconnectDatabase();' : ''}
    ${stats.hasCaching ? 'await disconnectRedis();' : ''}
    logger.info('Graceful shutdown complete');
    process.exit(0);
  });

  setTimeout(() => {
    logger.error('Forced shutdown — could not close connections in time');
    process.exit(1);
  }, 30000);
}

process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));

bootstrap();

export default app;
`;
}

function envExampleFile(analysis) {
  const { stats } = analysis;
  let env = `# ── Server ────────────────────────────────────────────
NODE_ENV=development
PORT=3000
CORS_ORIGIN=http://localhost:5173

`;

  if (stats.dbCount > 0) {
    env += stats.isPostgres
      ? `# ── PostgreSQL ───────────────────────────────────────\nDATABASE_URL=postgresql://admin:secret@localhost:5432/app\n\n`
      : `# ── MongoDB ───────────────────────────────────────────\nMONGODB_URI=mongodb://localhost:27017/app\n\n`;
  }

  if (stats.hasCaching) {
    env += `# ── Redis ─────────────────────────────────────────────\nREDIS_URL=redis://localhost:6379\n\n`;
  }

  if (stats.hasAuth) {
    env += `# ── Auth ──────────────────────────────────────────────\nJWT_SECRET=your-super-secret-key-change-this-in-production\nJWT_EXPIRES_IN=7d\nBCRYPT_ROUNDS=12\n`;
  }

  return env;
}

function eslintFile(projectConfig) {
  const ts = isTS(projectConfig.language);
  if (!ts) {
    return JSON.stringify({
      env: { node: true, es2022: true, jest: true },
      extends: 'eslint:recommended',
      parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
      rules: { 'no-unused-vars': 'warn' },
    }, null, 2);
  }
  return JSON.stringify({
    env: { node: true, es2022: true, jest: true },
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint'],
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
    parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
    rules: { 'no-unused-vars': 'off', '@typescript-eslint/no-unused-vars': 'warn' },
  }, null, 2);
}

function prettierFile() {
  return JSON.stringify({
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
  }, null, 2);
}

function gitignoreFile() {
  return `node_modules/\n.env\ncoverage/\ndist/\n*.log\n`;
}
