export const ARCHITECTURE_TEMPLATES = [
  {
    id: 'mern-ecommerce',
    name: 'E-Commerce Platform',
    category: 'Full Stack',
    description: 'Complete multi-service e-commerce backend with auth, product catalog, orders, payments, and notification pipeline.',
    tags: ['MERN', 'Microservices', 'Queue', 'Cache'],
    complexity: 'advanced',
    nodeCount: 12,
    previewImage: null,
    author: 'Architect.io',
    featured: true,
    nodes: [
      { id: 't1-cdn', type: 'cdnNode', position: { x: 500, y: 0 }, data: { provider: 'CloudFront CDN', redirectType: 'HTTPS Redirect', layer: 'gateway' } },
      { id: 't1-lb', type: 'loadBalancerNode', position: { x: 500, y: 150 }, data: { algorithm: 'Round Robin / Sticky', healthPath: 'health', layer: 'gateway' } },
      { id: 't1-gateway', type: 'apiNode', position: { x: 500, y: 300 }, data: { route: 'API Gateway Router', authEnabled: true, layer: 'gateway' } },
      { id: 't1-auth', type: 'authNode', position: { x: 120, y: 480 }, data: { method: 'JWT + OAuth2 / Auth Service', layer: 'application' } },
      { id: 't1-products', type: 'apiNode', position: { x: 380, y: 480 }, data: { route: '/api/v1/products', authEnabled: false, layer: 'application' } },
      { id: 't1-orders', type: 'apiNode', position: { x: 640, y: 480 }, data: { route: '/api/v1/orders', authEnabled: true, layer: 'application' } },
      { id: 't1-payments', type: 'apiNode', position: { x: 900, y: 480 }, data: { route: '/api/v1/payments', authEnabled: true, layer: 'application' } },
      { id: 't1-mongodb', type: 'dbNode', position: { x: 300, y: 680 }, data: { type: 'MongoDB Atlas', layer: 'data' } },
      { id: 't1-redis', type: 'cacheNode', position: { x: 600, y: 680 }, data: { provider: 'Redis Cache Layer', ttl: 3600, layer: 'data' } },
      { id: 't1-s3', type: 'storageNode', position: { x: 900, y: 680 }, data: { provider: 'AWS S3 Product Assets', layer: 'data' } },
      { id: 't1-queue', type: 'queueNode', position: { x: 640, y: 880 }, data: { broker: 'AWS SQS (Order Events)', topic: 'order-events', layer: 'messaging' } },
      { id: 't1-notif', type: 'logicNode', position: { x: 640, y: 1060 }, data: { hook: 'Notification Worker', layer: 'application' } },
    ],
    edges: [
      { id: 'e-cdn-lb', source: 't1-cdn', target: 't1-lb', label: 'HTTPS' },
      { id: 'e-lb-gw', source: 't1-lb', target: 't1-gateway', label: 'Route' },
      { id: 'e-gw-auth', source: 't1-gateway', target: 't1-auth', label: 'Auth' },
      { id: 'e-gw-prod', source: 't1-gateway', target: 't1-products', label: 'REST' },
      { id: 'e-gw-ord', source: 't1-gateway', target: 't1-orders', label: 'REST' },
      { id: 'e-gw-pay', source: 't1-gateway', target: 't1-payments', label: 'REST' },
      { id: 'e-prod-mongo', source: 't1-products', target: 't1-mongodb' },
      { id: 'e-prod-redis', source: 't1-products', target: 't1-redis', label: 'Cache' },
      { id: 'e-prod-s3', source: 't1-products', target: 't1-s3', label: 'Store' },
      { id: 'e-ord-mongo', source: 't1-orders', target: 't1-mongodb' },
      { id: 'e-ord-queue', source: 't1-orders', target: 't1-queue', label: 'Publish' },
      { id: 'e-queue-notif', source: 't1-queue', target: 't1-notif', label: 'Consume' },
    ],
  },

  {
    id: 'saas-multitenant',
    name: 'SaaS Multi-Tenant App',
    category: 'SaaS',
    description: 'Multi-tenant SaaS architecture with tenant isolation, subscription management, and per-tenant data segregation.',
    tags: ['SaaS', 'Multi-tenant', 'Auth', 'Subscriptions'],
    complexity: 'advanced',
    nodeCount: 10,
    featured: true,
    nodes: [
      { id: 't2-gateway', type: 'apiNode', position: { x: 400, y: 40 }, data: { route: 'API Gateway Tenant Router', authEnabled: true, layer: 'gateway' } },
      { id: 't2-auth', type: 'authNode', position: { x: 150, y: 220 }, data: { method: 'JWT Credentials / Auth Service', layer: 'application' } },
      { id: 't2-tenant', type: 'apiNode', position: { x: 400, y: 220 }, data: { route: '/api/v1/tenants', authEnabled: true, layer: 'application' } },
      { id: 't2-billing', type: 'apiNode', position: { x: 650, y: 220 }, data: { route: '/api/v1/billing', authEnabled: true, layer: 'application' } },
      { id: 't2-app', type: 'apiNode', position: { x: 400, y: 420 }, data: { route: 'Core Application API', authEnabled: true, layer: 'application' } },
      { id: 't2-mongo', type: 'dbNode', position: { x: 200, y: 620 }, data: { type: 'MongoDB (Tenant A Isolation)', layer: 'data' } },
      { id: 't2-mongo2', type: 'dbNode', position: { x: 500, y: 620 }, data: { type: 'MongoDB (Tenant B Isolation)', layer: 'data' } },
      { id: 't2-redis', type: 'cacheNode', position: { x: 800, y: 420 }, data: { provider: 'Redis Session Store', ttl: 1800, layer: 'data' } },
      { id: 't2-stripe', type: 'webhookNode', position: { x: 900, y: 220 }, data: { provider: 'Stripe Subscription API', direction: 'Outgoing', layer: 'client' } },
      { id: 't2-email', type: 'webhookNode', position: { x: 150, y: 420 }, data: { provider: 'SendGrid Email API', direction: 'Outgoing', layer: 'client' } },
    ],
    edges: [
      { id: 'e1', source: 't2-gateway', target: 't2-auth' },
      { id: 'e2', source: 't2-gateway', target: 't2-tenant' },
      { id: 'e3', source: 't2-gateway', target: 't2-billing' },
      { id: 'e4', source: 't2-gateway', target: 't2-app' },
      { id: 'e5', source: 't2-app', target: 't2-mongo' },
      { id: 'e6', source: 't2-app', target: 't2-mongo2' },
      { id: 'e7', source: 't2-auth', target: 't2-redis', label: 'Sessions' },
      { id: 'e8', source: 't2-billing', target: 't2-stripe', label: 'Webhooks' },
      { id: 'e9', source: 't2-auth', target: 't2-email', label: 'OTP / Welcome' },
    ],
  },

  {
    id: 'realtime-chat',
    name: 'Real-Time Chat System',
    category: 'Real-Time',
    description: 'WebSocket-powered chat with message persistence, presence tracking, and horizontal scaling via Redis pub/sub.',
    tags: ['WebSocket', 'Redis Pub/Sub', 'Real-Time', 'MongoDB'],
    complexity: 'intermediate',
    nodeCount: 8,
    featured: false,
    nodes: [
      { id: 't3-lb', type: 'loadBalancerNode', position: { x: 400, y: 40 }, data: { algorithm: 'Sticky Sessions (WS)', healthPath: 'healthz', layer: 'gateway' } },
      { id: 't3-ws1', type: 'apiNode', position: { x: 200, y: 240 }, data: { route: 'WebSocket Server Instance 1', authEnabled: true, layer: 'application' } },
      { id: 't3-ws2', type: 'apiNode', position: { x: 600, y: 240 }, data: { route: 'WebSocket Server Instance 2', authEnabled: true, layer: 'application' } },
      { id: 't3-redis-pubsub', type: 'cacheNode', position: { x: 400, y: 440 }, data: { provider: 'Redis Pub/Sub Message Bus', ttl: 300, layer: 'messaging' } },
      { id: 't3-redis-presence', type: 'cacheNode', position: { x: 700, y: 440 }, data: { provider: 'Redis Presence Tracker', ttl: 600, layer: 'data' } },
      { id: 't3-mongo', type: 'dbNode', position: { x: 100, y: 640 }, data: { type: 'MongoDB Message History', layer: 'data' } },
      { id: 't3-auth', type: 'authNode', position: { x: 400, y: 640 }, data: { method: 'JWT Session Token Verification', layer: 'application' } },
      { id: 't3-notif', type: 'logicNode', position: { x: 700, y: 640 }, data: { hook: 'Push Notification Worker', layer: 'application' } },
    ],
    edges: [
      { id: 'e1', source: 't3-lb', target: 't3-ws1', label: 'WS' },
      { id: 'e2', source: 't3-lb', target: 't3-ws2', label: 'WS' },
      { id: 'e3', source: 't3-ws1', target: 't3-redis-pubsub', label: 'Publish' },
      { id: 'e4', source: 't3-ws2', target: 't3-redis-pubsub', label: 'Subscribe' },
      { id: 'e5', source: 't3-ws1', target: 't3-mongo', label: 'Persist' },
      { id: 'e6', source: 't3-ws1', target: 't3-redis-presence', label: 'Presence' },
      { id: 'e7', source: 't3-ws1', target: 't3-auth', label: 'Verify JWT' },
      { id: 'e8', source: 't3-redis-pubsub', target: 't3-notif', label: 'Offline Push' },
    ],
  },

  {
    id: 'data-pipeline',
    name: 'Data Pipeline / ETL',
    category: 'Data Engineering',
    description: 'Event-driven ETL pipeline: ingest raw data, transform via workers, store in warehouse, and expose analytics API.',
    tags: ['ETL', 'Kafka', 'Data Warehouse', 'Analytics'],
    complexity: 'advanced',
    nodeCount: 9,
    featured: false,
    nodes: [
      { id: 't4-ingest', type: 'apiNode', position: { x: 400, y: 40 }, data: { route: 'Data Ingestion API Gateway', authEnabled: false, layer: 'gateway' } },
      { id: 't4-kafka', type: 'queueNode', position: { x: 400, y: 220 }, data: { broker: 'Kafka Broker', topic: 'raw-ingested-events', layer: 'messaging' } },
      { id: 't4-transformer', type: 'logicNode', position: { x: 200, y: 420 }, data: { hook: 'Transform & Normalize ETL', layer: 'application' } },
      { id: 't4-validator', type: 'logicNode', position: { x: 600, y: 420 }, data: { hook: 'Schema Validation Worker', layer: 'application' } },
      { id: 't4-kafka2', type: 'queueNode', position: { x: 400, y: 620 }, data: { broker: 'Kafka Broker', topic: 'processed-events', layer: 'messaging' } },
      { id: 't4-mongo', type: 'dbNode', position: { x: 150, y: 820 }, data: { type: 'MongoDB Raw Events Store', layer: 'data' } },
      { id: 't4-pg', type: 'dbNode', position: { x: 650, y: 820 }, data: { type: 'PostgreSQL Analytics DW', layer: 'data' } },
      { id: 't4-redis', type: 'cacheNode', position: { x: 400, y: 820 }, data: { provider: 'Redis Real-Time Metrics', ttl: 60, layer: 'data' } },
      { id: 't4-analytics', type: 'apiNode', position: { x: 800, y: 220 }, data: { route: '/api/v1/analytics-query', authEnabled: true, layer: 'application' } },
    ],
    edges: [
      { id: 'e1', source: 't4-ingest', target: 't4-kafka' },
      { id: 'e2', source: 't4-kafka', target: 't4-transformer' },
      { id: 'e3', source: 't4-kafka', target: 't4-validator' },
      { id: 'e4', source: 't4-transformer', target: 't4-kafka2' },
      { id: 'e5', source: 't4-validator', target: 't4-kafka2' },
      { id: 'e6', source: 't4-kafka2', target: 't4-mongo' },
      { id: 'e7', source: 't4-kafka2', target: 't4-pg' },
      { id: 'e8', source: 't4-kafka2', target: 't4-redis' },
      { id: 'e9', source: 't4-analytics', target: 't4-pg' },
    ],
  },

  {
    id: 'serverless-api',
    name: 'Serverless REST API',
    category: 'Serverless',
    description: 'Lambda-based serverless API with DynamoDB, S3, API Gateway authorizer, and CloudWatch monitoring.',
    tags: ['Serverless', 'Lambda', 'DynamoDB', 'AWS'],
    complexity: 'intermediate',
    nodeCount: 7,
    featured: false,
    nodes: [
      { id: 't5-gw', type: 'apiNode', position: { x: 400, y: 40 }, data: { route: 'AWS API Gateway Routing', authEnabled: true, layer: 'gateway' } },
      { id: 't5-auth-lambda', type: 'logicNode', position: { x: 150, y: 240 }, data: { hook: 'Authorizer Lambda Function', layer: 'application' } },
      { id: 't5-api-lambda', type: 'logicNode', position: { x: 500, y: 240 }, data: { hook: 'REST API Handler Lambda', layer: 'application' } },
      { id: 't5-dynamo', type: 'dbNode', position: { x: 300, y: 460 }, data: { type: 'Amazon DynamoDB Store', layer: 'data' } },
      { id: 't5-s3', type: 'storageNode', position: { x: 700, y: 460 }, data: { provider: 'AWS S3 Assets Bucket', layer: 'data' } },
      { id: 't5-cloudwatch', type: 'middlewareNode', position: { x: 900, y: 240 }, data: { middleware: 'CloudWatch Observability Logging', layer: 'observability' } },
      { id: 't5-sqs', type: 'queueNode', position: { x: 500, y: 660 }, data: { broker: 'AWS SQS Async Jobs Queue', topic: 'job-queue', layer: 'messaging' } },
    ],
    edges: [
      { id: 'e1', source: 't5-gw', target: 't5-auth-lambda', label: 'Authorize' },
      { id: 'e2', source: 't5-gw', target: 't5-api-lambda', label: 'Invoke' },
      { id: 'e3', source: 't5-api-lambda', target: 't5-dynamo', label: 'CRUD' },
      { id: 'e4', source: 't5-api-lambda', target: 't5-s3', label: 'Upload' },
      { id: 'e5', source: 't5-api-lambda', target: 't5-cloudwatch', label: 'Logs' },
      { id: 'e6', source: 't5-api-lambda', target: 't5-sqs', label: 'Enqueue' },
    ],
  },
];
