import { analyzeArchitecture } from './architectureAnalyzer';

// ─── Main Entry Point ───────────────────────────────────────────────
export function generateCode(nodes, edges, format = 'express', documentation = '') {
  const analysis = analyzeArchitecture(nodes, edges);

  switch (format) {
    case 'express':     return generateExpressProject(analysis, documentation);
    case 'docker':      return generateDockerCompose(analysis);
    case 'env':         return generateEnvFile(analysis);
    case 'readme':      return generateArchitectureReadme(analysis, documentation);
    default:            return generateExpressProject(analysis, documentation);
  }
}

// ─── Express.js / Node.js Generator ─────────────────────────────────
function generateExpressProject(analysis, documentation = '') {
  const { entities, dbNodes, queueNodes, stats } = analysis;
  const files = {};

  // package.json
  const deps = {
    express: '^4.18.2',
    dotenv: '^16.0.3',
    cors: '^2.8.5',
    helmet: '^7.1.0',
  };

  if (stats.dbCount > 0 && stats.isMongo) deps.mongoose = '^8.0.0';
  if (stats.dbCount > 0 && stats.isPostgres) deps.pg = '^8.11.0';
  if (stats.hasCaching) deps.ioredis = '^5.3.2';
  if (stats.hasAuth) { deps.jsonwebtoken = '^9.0.0'; deps.bcryptjs = '^2.4.3'; }
  if (stats.hasMessaging) deps.amqplib = '^0.10.3';

  files['package.json'] = JSON.stringify({
    name: 'architect-io-generated',
    version: '1.0.0',
    description: `Generated by Architect.io — ${stats.totalNodes} nodes, ${stats.totalEdges} connections`,
    main: 'src/server.js',
    type: 'module',
    scripts: {
      start: 'node src/server.js',
      dev: 'nodemon src/server.js',
      test: 'jest',
    },
    dependencies: deps,
    devDependencies: {
      nodemon: '^3.0.0',
      jest: '^29.0.0',
    },
  }, null, 2);

  // src/server.js
  files['src/server.js'] = generateServerFile(analysis);

  // src/config/database.js
  if (stats.dbCount > 0) {
    files['src/config/database.js'] = generateDatabaseConfig(analysis);
  }

  // src/config/redis.js
  if (stats.hasCaching) {
    files['src/config/redis.js'] = generateRedisConfig(analysis);
  }

  // One route file per entity that is connected to an API
  entities.forEach((entity) => {
    const name = toKebabCase(entity.data?.name || entity.id);
    const camelName = toCamelCase(entity.data?.name || entity.id);
    files[`src/routes/${name}.routes.js`] = generateRouteFile(entity, analysis);
    files[`src/controllers/${name}.controller.js`] = generateControllerFile(entity, analysis);
    if (stats.dbCount > 0) {
      files[`src/models/${name}.model.js`] = generateModelFile(entity, analysis);
    }
    files[`src/services/${name}.service.js`] = generateServiceFile(entity, analysis);
  });

  // Middleware
  if (stats.hasAuth) {
    files['src/middleware/auth.middleware.js'] = generateAuthMiddleware(analysis);
  }
  files['src/middleware/error.middleware.js'] = generateErrorMiddleware();
  files['src/middleware/logger.middleware.js'] = generateLoggerMiddleware();

  // Message consumers
  queueNodes.forEach((queue) => {
    const name = toKebabCase(queue.data?.label || queue.id);
    files[`src/consumers/${name}.consumer.js`] = generateConsumerFile(queue, analysis);
  });

  files['README.md'] = generateArchitectureReadme(analysis, documentation);

  return formatAsFileTree(files);
}

// ─── Component Generators ─────────────────────────────────────────────
function generateServerFile(analysis) {
  const { entities, stats } = analysis;
  // Determine which entities actually have an API connected
  const apiEntities = entities.filter(e => analysis.entityApiMap[e.id] && analysis.entityApiMap[e.id].length > 0);
  
  const imports = apiEntities.map((s) => {
    const name = toCamelCase(s.data?.name || s.id);
    const path = toKebabCase(s.data?.name || s.id);
    return `import ${name}Router from './routes/${path}.routes.js';`;
  }).join('\n');

  const routeRegistrations = apiEntities.map((s) => {
    const name = toCamelCase(s.data?.name || s.id);
    const path = toKebabCase(s.data?.name || s.id);
    return `app.use('/api/v1/${path}', ${name}Router);`;
  }).join('\n');

  return `/**
 * server.js — Generated by Architect.io
 * Architecture: ${stats.totalNodes} nodes, ${stats.totalEdges} connections
 * Services: ${apiEntities.length} | Databases: ${stats.dbCount}
 */

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';
${stats.dbCount > 0 ? "import { connectDatabase } from './config/database.js';" : ''}
${stats.hasCaching ? "import { connectRedis } from './config/redis.js';" : ''}
import { errorHandler } from './middleware/error.middleware.js';
import { requestLogger } from './middleware/logger.middleware.js';
${stats.hasAuth ? "import { authMiddleware } from './middleware/auth.middleware.js';" : ''}
${imports}

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

// ── Security & Parsing Middleware ──
app.use(helmet());
app.use(cors({ origin: process.env.CORS_ORIGIN || '*', credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(requestLogger);

// ── Health Check ──
app.get('/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString(), uptime: process.uptime() });
});

// ── API Routes ──
${routeRegistrations}

// ── Error Handling ──
app.use(errorHandler);

// ── Bootstrap ──
async function bootstrap() {
  try {
    ${stats.dbCount > 0 ? 'await connectDatabase();' : ''}
    ${stats.hasCaching ? 'await connectRedis();' : ''}
    app.listen(PORT, () => {
      console.log(\`🚀 Server running on http://localhost:\${PORT}\`);
      console.log(\`📊 Architecture: ${apiEntities.length} services, ${stats.dbCount} data stores\`);
    });
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
}

bootstrap();
`;
}

function generateDatabaseConfig(analysis) {
  if (analysis.stats.isPostgres) {
    return `import { Pool } from 'pg';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL
});

export const connectDatabase = async () => {
  try {
    await pool.connect();
    console.log('PostgreSQL connected');
  } catch (err) {
    console.error('PostgreSQL connection error', err);
    process.exit(1);
  }
};

export default pool;`;
  }
  
  return `import mongoose from 'mongoose';

export const connectDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB connected');
  } catch (err) {
    console.error('MongoDB connection error', err);
    process.exit(1);
  }
};`;
}

function generateRedisConfig(analysis) {
  return `import Redis from 'ioredis';

let redisClient;

export const connectRedis = () => {
  redisClient = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');
  
  redisClient.on('connect', () => {
    console.log('Redis connected');
  });
  
  redisClient.on('error', (err) => {
    console.error('Redis error', err);
  });
  
  return redisClient;
};

export const getRedisClient = () => redisClient;`;
}

function generateRouteFile(entity, analysis) {
  const camelName = toCamelCase(entity.data?.name || entity.id);
  const kebabName = toKebabCase(entity.data?.name || entity.id);
  
  // Check auth requirements
  const apiNodeIds = analysis.entityApiMap[entity.id] || [];
  let requiresAuth = false;
  apiNodeIds.forEach(id => {
    const apiNode = analysis.apiNodes.find(n => n.id === id);
    if (apiNode && apiNode.data?.authEnabled) requiresAuth = true;
  });

  return `import { Router } from 'express';
import * as ${camelName}Controller from '../controllers/${kebabName}.controller.js';
${requiresAuth ? "import { authMiddleware } from '../middleware/auth.middleware.js';" : ''}

const router = Router();
${requiresAuth ? '\nrouter.use(authMiddleware);\n' : ''}
router.get('/', ${camelName}Controller.findAll);
router.get('/:id', ${camelName}Controller.findOne);
router.post('/', ${camelName}Controller.create);
router.put('/:id', ${camelName}Controller.update);
router.delete('/:id', ${camelName}Controller.remove);

export default router;`;
}

function generateControllerFile(entity, analysis) {
  const camelName = toCamelCase(entity.data?.name || entity.id);
  const kebabName = toKebabCase(entity.data?.name || entity.id);
  
  return `import * as ${camelName}Service from '../services/${kebabName}.service.js';

export const findAll = async (req, res, next) => {
  try {
    const results = await ${camelName}Service.findAll(req.query);
    res.json(results);
  } catch (err) {
    next(err);
  }
};

export const findOne = async (req, res, next) => {
  try {
    const result = await ${camelName}Service.findById(req.params.id);
    if (!result) return res.status(404).json({ message: 'Not found' });
    res.json(result);
  } catch (err) {
    next(err);
  }
};

export const create = async (req, res, next) => {
  try {
    const result = await ${camelName}Service.create(req.body);
    res.status(201).json(result);
  } catch (err) {
    next(err);
  }
};

export const update = async (req, res, next) => {
  try {
    const result = await ${camelName}Service.update(req.params.id, req.body);
    if (!result) return res.status(404).json({ message: 'Not found' });
    res.json(result);
  } catch (err) {
    next(err);
  }
};

export const remove = async (req, res, next) => {
  try {
    const result = await ${camelName}Service.remove(req.params.id);
    if (!result) return res.status(404).json({ message: 'Not found' });
    res.status(204).send();
  } catch (err) {
    next(err);
  }
};`;
}

function generateModelFile(entity, analysis) {
  const pascalName = toPascalCase(entity.data?.name || entity.id);
  
  if (analysis.stats.isPostgres) {
    return `// Using raw PG. In a real app you might use Prisma or Sequelize or Drizzle.
import pool from '../config/database.js';

export class ${pascalName}Model {
  static async findAll() {
    const { rows } = await pool.query('SELECT * FROM ${toKebabCase(pascalName)}');
    return rows;
  }
  
  static async findById(id) {
    const { rows } = await pool.query('SELECT * FROM ${toKebabCase(pascalName)} WHERE id = $1', [id]);
    return rows[0];
  }
  
  static async create(data) {
    const keys = Object.keys(data).join(', ');
    const values = Object.values(data);
    const placeholders = values.map((_, i) => \`$\${i + 1}\`).join(', ');
    const { rows } = await pool.query(
      \`INSERT INTO ${toKebabCase(pascalName)} (\${keys}) VALUES (\${placeholders}) RETURNING *\`,
      values
    );
    return rows[0];
  }
}`;
  }

  // MongoDB schema mapping
  const fields = entity.data?.fields || [];
  const schemaFields = fields.map(f => {
    let type = 'String';
    if (f.type === 'number') type = 'Number';
    if (f.type === 'boolean') type = 'Boolean';
    if (f.type === 'date') type = 'Date';
    return `  ${f.name}: { type: ${type}, required: ${f.required ? 'true' : 'false'} }`;
  }).join(',\n');

  return `import mongoose from 'mongoose';

const schema = new mongoose.Schema({
${schemaFields || '  // Add fields here'}
}, { timestamps: true });

export const ${pascalName} = mongoose.model('${pascalName}', schema);`;
}

function generateServiceFile(entity, analysis) {
  const pascalName = toPascalCase(entity.data?.name || entity.id);
  const isMongo = analysis.stats.isMongo;
  
  return `import { ${pascalName} ${!isMongo ? 'as Model' : ''} } from '../models/${toKebabCase(pascalName)}.model.js';

export const findAll = async (query = {}) => {
  ${isMongo ? `return await ${pascalName}.find(query);` : `return await Model.findAll();`}
};

export const findById = async (id) => {
  ${isMongo ? `return await ${pascalName}.findById(id);` : `return await Model.findById(id);`}
};

export const create = async (data) => {
  ${isMongo ? `const doc = new ${pascalName}(data);\n  return await doc.save();` : `return await Model.create(data);`}
};

export const update = async (id, data) => {
  ${isMongo ? `return await ${pascalName}.findByIdAndUpdate(id, data, { new: true });` : `// Implement PG update\n  return null;`}
};

export const remove = async (id) => {
  ${isMongo ? `return await ${pascalName}.findByIdAndDelete(id);` : `// Implement PG delete\n  return null;`}
};`;
}

function generateAuthMiddleware(analysis) {
  return `import jwt from 'jsonwebtoken';

export const authMiddleware = (req, res, next) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ message: 'Unauthorized' });
  }

  const token = authHeader.split(' ')[1];
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'secret');
    req.user = decoded;
    next();
  } catch (err) {
    return res.status(401).json({ message: 'Invalid token' });
  }
};`;
}

function generateErrorMiddleware() {
  return `export const errorHandler = (err, req, res, next) => {
  console.error(err.stack);
  res.status(err.status || 500).json({
    error: {
      message: err.message || 'Internal Server Error',
      ...(process.env.NODE_ENV === 'development' && { stack: err.stack })
    }
  });
};`;
}

function generateLoggerMiddleware() {
  return `export const requestLogger = (req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    console.log(\`[\${new Date().toISOString()}] \${req.method} \${req.originalUrl} \${res.statusCode} - \${duration}ms\`);
  });
  next();
};`;
}

function generateConsumerFile(queue, analysis) {
  return `// Queue consumer logic for ${queue.data?.topic || 'default-topic'}\nexport const startConsumer = async () => {\n  console.log('Consumer started');\n};`;
}

// ─── Docker Compose Generator ─────────────────────────────────────────
function generateDockerCompose(analysis) {
  const { apiNodes, dbNodes, queueNodes, cacheNodes } = analysis;
  const composeServices = {};

  // Application services
  composeServices['api'] = {
    build: { context: '.', dockerfile: 'Dockerfile' },
    ports: ['3000:3000'],
    environment: ['NODE_ENV=production', 'PORT=3000'],
    depends_on: [],
    restart: 'unless-stopped',
    networks: ['app-network'],
  };

  // Data stores
  dbNodes.forEach((ds) => {
    const name = toKebabCase(ds.data?.label || ds.id);
    if (ds.data?.type === 'mongodb') {
      composeServices[name] = {
        image: 'mongo:7.0',
        ports: ['27017:27017'],
        volumes: [`${name}_data:/data/db`],
        environment: ['MONGO_INITDB_ROOT_USERNAME=admin', 'MONGO_INITDB_ROOT_PASSWORD=secret'],
        networks: ['app-network'],
      };
      composeServices['api'].depends_on.push(name);
    } else if (ds.data?.type === 'postgresql') {
      composeServices[name] = {
        image: 'postgres:16-alpine',
        ports: ['5432:5432'],
        volumes: [`${name}_data:/var/lib/postgresql/data`],
        environment: ['POSTGRES_USER=admin', 'POSTGRES_PASSWORD=secret', `POSTGRES_DB=${name}`],
        networks: ['app-network'],
      };
      composeServices['api'].depends_on.push(name);
    }
  });

  cacheNodes.forEach((ds) => {
    const name = toKebabCase(ds.data?.label || ds.id);
    composeServices[name] = {
      image: 'redis:7-alpine',
      ports: ['6379:6379'],
      volumes: [`${name}_data:/data`],
      command: 'redis-server --appendonly yes',
      networks: ['app-network'],
    };
    composeServices['api'].depends_on.push(name);
  });

  // Message queues
  queueNodes.forEach((q) => {
    const name = toKebabCase(q.data?.label || q.id);
    composeServices[name] = {
      image: 'rabbitmq:3.12-management-alpine',
      ports: ['5672:5672', '15672:15672'],
      networks: ['app-network'],
    };
  });

  const volumes = {};
  dbNodes.forEach((ds) => { volumes[`${toKebabCase(ds.data?.label || ds.id)}_data`] = {}; });
  cacheNodes.forEach((ds) => { volumes[`${toKebabCase(ds.data?.label || ds.id)}_data`] = {}; });

  const compose = {
    version: '3.9',
    services: composeServices,
    networks: { 'app-network': { driver: 'bridge' } },
    volumes,
  };

  return `# docker-compose.yml — Generated by Architect.io
# Architecture: ${analysis.stats.totalNodes} nodes, ${analysis.stats.totalEdges} connections

${JSON.stringify(compose, null, 2).replace(/"([^"]+)":/g, '$1:')}`; // basic yaml like print
}

// ─── .env Generator ──────────────────────────────────────────────────
function generateEnvFile(analysis) {
  const { dbNodes, cacheNodes, stats } = analysis;
  let env = `# .env — Generated by Architect.io
# Copy this file to .env.local and fill in your values

# ── Server ────────────────────────────────────────────
NODE_ENV=development
PORT=3000
CORS_ORIGIN=http://localhost:5173

`;

  dbNodes.forEach((ds) => {
    const name = (ds.data?.label || ds.id).toUpperCase().replace(/\s/g, '_');
    if (ds.data?.type === 'mongodb') {
      env += `# ── MongoDB ──
MONGODB_URI=mongodb://localhost:27017/${toKebabCase(ds.data?.dbName || 'app')}
`;
    } else if (ds.data?.type === 'postgresql') {
      env += `# ── PostgreSQL ──
DATABASE_URL=postgresql://admin:secret@localhost:5432/${toKebabCase(ds.data?.dbName || 'app')}
`;
    }
  });

  cacheNodes.forEach((ds) => {
    env += `# ── Redis ──
REDIS_URL=redis://localhost:6379
`;
  });

  if (stats.hasAuth) {
    env += `# ── Auth ─────────────────────────────────────────────
JWT_SECRET=your-super-secret-key-change-this-in-production
JWT_EXPIRES_IN=7d
BCRYPT_ROUNDS=12
`;
  }

  return env;
}

// ─── Readme Generator ──────────────────────────────────────────────────
function generateArchitectureReadme(analysis, documentation) {
  const { stats } = analysis;
  
  const autoGenerated = `## Architecture Overview
- **Nodes**: ${stats.totalNodes}
- **Connections**: ${stats.totalEdges}
- **Entities**: ${stats.entityCount}
- **Databases**: ${stats.dbCount} (${stats.isPostgres ? 'PostgreSQL' : stats.isMongo ? 'MongoDB' : 'None'})
- **Caching**: ${stats.hasCaching ? 'Yes' : 'No'}
- **Auth**: ${stats.hasAuth ? 'Yes' : 'No'}
- **Messaging/Queues**: ${stats.hasMessaging ? 'Yes' : 'No'}

## Getting Started

1. \`npm install\`
2. Configure \`.env\`
3. \`npm run dev\`

## Docker

Run \`docker-compose up -d\` to spin up your infrastructure components.
`;

  if (documentation && documentation.trim()) {
    return documentation;
  }

  return `# Generated Project\n\nThis backend was automatically generated by **Architect.io**.\n\n${autoGenerated}`;
}

// ─── Helper Utilities ─────────────────────────────────────────────────
function toKebabCase(str) {
  return str?.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || 'service';
}

function toCamelCase(str) {
  return str?.replace(/[-\s](.)/g, (_, c) => c.toUpperCase()).replace(/^./, c => c.toLowerCase()) || 'service';
}

function toPascalCase(str) {
  return str?.replace(/[-\s](.)/g, (_, c) => c.toUpperCase()).replace(/^./, c => c.toUpperCase()) || 'Service';
}

function formatAsFileTree(files) {
  return Object.entries(files).map(([path, content]) => ({
    path,
    content,
    language: path.endsWith('.json') ? 'json' : path.endsWith('.yml') ? 'yaml' : 'javascript',
  }));
}
