import { analyzeArchitecture } from './architectureAnalyzer';
import GeneratorRegistry from '../generators/index.js';

// ─── Main Entry Point ───────────────────────────────────────────────
export function generateCode(nodes, edges, format = 'express', documentation = '', projectConfig = {}) {
  const analysis = analyzeArchitecture(nodes, edges);

  switch (format) {
    case 'express':     return GeneratorRegistry.get('mern').generate(analysis, projectConfig);
    case 'docker':      return generateDockerCompose(analysis);
    case 'env':         return generateEnvFile(analysis);
    case 'readme':      return generateArchitectureReadme(analysis, documentation);
    default:            return GeneratorRegistry.get('mern').generate(analysis, projectConfig);
  }
}

// ─── Docker Compose Generator ─────────────────────────────────────────
// (This drives the standalone "Docker Compose" preview tab; the full
// generated project also gets its own Dockerfile/compose via DockerEmitter.)
function generateDockerCompose(analysis) {
  const { dbNodes, queueNodes, cacheNodes } = analysis;
  const composeServices = {};

  // Application services
  composeServices['api'] = {
    build: { context: '.', dockerfile: 'Dockerfile' },
    ports: ['3000:3000'],
    environment: ['NODE_ENV=production', 'PORT=3000'],
    depends_on: [],
    restart: 'unless-stopped',
    networks: ['app-network'],
  };

  // Data stores
  dbNodes.forEach((ds) => {
    const name = toKebabCase(ds.data?.label || ds.id);
    if (ds.data?.type === 'mongodb') {
      composeServices[name] = {
        image: 'mongo:7.0',
        ports: ['27017:27017'],
        volumes: [`${name}_data:/data/db`],
        environment: ['MONGO_INITDB_ROOT_USERNAME=admin', 'MONGO_INITDB_ROOT_PASSWORD=secret'],
        networks: ['app-network'],
      };
      composeServices['api'].depends_on.push(name);
    } else if (ds.data?.type === 'postgresql') {
      composeServices[name] = {
        image: 'postgres:16-alpine',
        ports: ['5432:5432'],
        volumes: [`${name}_data:/var/lib/postgresql/data`],
        environment: ['POSTGRES_USER=admin', 'POSTGRES_PASSWORD=secret', `POSTGRES_DB=${name}`],
        networks: ['app-network'],
      };
      composeServices['api'].depends_on.push(name);
    }
  });

  cacheNodes.forEach((ds) => {
    const name = toKebabCase(ds.data?.label || ds.id);
    composeServices[name] = {
      image: 'redis:7-alpine',
      ports: ['6379:6379'],
      volumes: [`${name}_data:/data`],
      command: 'redis-server --appendonly yes',
      networks: ['app-network'],
    };
    composeServices['api'].depends_on.push(name);
  });

  // Message queues
  queueNodes.forEach((q) => {
    const name = toKebabCase(q.data?.label || q.id);
    composeServices[name] = {
      image: 'rabbitmq:3.12-management-alpine',
      ports: ['5672:5672', '15672:15672'],
      networks: ['app-network'],
    };
  });

  const volumes = {};
  dbNodes.forEach((ds) => { volumes[`${toKebabCase(ds.data?.label || ds.id)}_data`] = {}; });
  cacheNodes.forEach((ds) => { volumes[`${toKebabCase(ds.data?.label || ds.id)}_data`] = {}; });

  const compose = {
    version: '3.9',
    services: composeServices,
    networks: { 'app-network': { driver: 'bridge' } },
    volumes,
  };

  return `# docker-compose.yml — Generated by Architect.io
# Architecture: ${analysis.stats.totalNodes} nodes, ${analysis.stats.totalEdges} connections

${JSON.stringify(compose, null, 2).replace(/"([^"]+)":/g, '$1:')}`; // basic yaml like print
}

// ─── .env Generator ──────────────────────────────────────────────────
function generateEnvFile(analysis) {
  const { dbNodes, cacheNodes, stats } = analysis;
  let env = `# .env — Generated by Architect.io
# Copy this file to .env.local and fill in your values

# ── Server ────────────────────────────────────────────
NODE_ENV=development
PORT=3000
CORS_ORIGIN=http://localhost:5173

`;

  dbNodes.forEach((ds) => {
    if (ds.data?.type === 'mongodb') {
      env += `# ── MongoDB ──
MONGODB_URI=mongodb://localhost:27017/${toKebabCase(ds.data?.dbName || 'app')}
`;
    } else if (ds.data?.type === 'postgresql') {
      env += `# ── PostgreSQL ──
DATABASE_URL=postgresql://admin:secret@localhost:5432/${toKebabCase(ds.data?.dbName || 'app')}
`;
    }
  });

  cacheNodes.forEach(() => {
    env += `# ── Redis ──
REDIS_URL=redis://localhost:6379
`;
  });

  if (stats.hasAuth) {
    env += `# ── Auth ─────────────────────────────────────────────
JWT_SECRET=your-super-secret-key-change-this-in-production
JWT_EXPIRES_IN=7d
BCRYPT_ROUNDS=12
`;
  }

  return env;
}

// ─── Readme Generator ──────────────────────────────────────────────────
function generateArchitectureReadme(analysis, documentation) {
  const { stats } = analysis;

  const autoGenerated = `## Architecture Overview
- **Nodes**: ${stats.totalNodes}
- **Connections**: ${stats.totalEdges}
- **Entities**: ${stats.entityCount}
- **Databases**: ${stats.dbCount} (${stats.isPostgres ? 'PostgreSQL' : stats.isMongo ? 'MongoDB' : 'None'})
- **Caching**: ${stats.hasCaching ? 'Yes' : 'No'}
- **Auth**: ${stats.hasAuth ? 'Yes' : 'No'}
- **Messaging/Queues**: ${stats.hasMessaging ? 'Yes' : 'No'}

## Getting Started

1. \`npm install\`
2. Configure \`.env\`
3. \`npm run dev\`

## Docker

Run \`docker-compose up -d\` to spin up your infrastructure components.
`;

  if (documentation && documentation.trim()) {
    return documentation;
  }

  return `# Generated Project\n\nThis backend was automatically generated by **Architect.io**.\n\n${autoGenerated}`;
}

// ─── Helper Utilities ─────────────────────────────────────────────────
function toKebabCase(str) {
  return str?.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || 'service';
}
