/**
 * documentationGenerator.js — Architect.io
 * Generates rich narrative documentation from the visual architecture graph.
 */

import { analyzeArchitecture } from './architectureAnalyzer';

// ─── Main Entry ───────────────────────────────────────────────────────
export function generateDocumentation(nodes, edges, projectName = 'My Architecture') {
  if (!nodes || nodes.length === 0) return getEmptyDocPlaceholder();

  const analysis = analyzeArchitecture(nodes, edges);

  const sections = [
    generateOverviewSection(analysis, projectName),
    generateFlowSection(analysis),
    generateComponentDetailsSection(analysis),
    generateMermaidDiagram(nodes, edges),
    generateFailureModesSection(analysis),
    generateScalabilitySection(analysis),
    generateTechStackSection(analysis),
    generateDeploymentSection(analysis),
  ];

  return sections.join('\n\n---\n\n');
}

// ─── Section: Overview ────────────────────────────────────────────────
function generateOverviewSection(analysis, projectName) {
  const { stats, entryNodes, dbNodes, cacheNodes, queueNodes } = analysis;

  const entryDesc = entryNodes.map((n) => getNodeLabel(n)).join(', ') || 'the client';
  const dbDesc = dbNodes.map((n) => getNodeLabel(n)).join(', ') || 'a data store';

  return `# ${projectName} — Architecture Documentation

> Auto-generated by Architect.io from your visual architecture diagram.

## Overview

This architecture consists of **${stats.totalNodes} components** connected by **${stats.totalEdges} data flows**.
The system includes ${stats.apiCount} API endpoint${stats.apiCount !== 1 ? 's' : ''}, ${stats.dbCount} data store${stats.dbCount !== 1 ? 's' : ''}, and ${stats.entityCount} data model${stats.entityCount !== 1 ? 's' : ''}.

Traffic enters through **${entryDesc}** and ultimately persists to **${dbDesc}**.
${stats.hasAuth ? '\n🔐 **Authentication** is enforced at the API layer via JWT tokens.' : ''}
${stats.hasCaching ? '\n⚡ **Caching** (Redis) is present to reduce database load and improve response times.' : ''}
${stats.hasMessaging ? '\n📨 **Async messaging** decouples background processing via a message queue.' : ''}
${stats.hasMailer ? '\n📧 **Email service** is integrated for transactional notifications.' : ''}
${stats.hasStorage ? '\n🪣 **Object storage** handles file uploads and static assets.' : ''}
${stats.hasCron ? '\n⏱️ **Scheduled jobs** automate recurring background tasks.' : ''}
${stats.hasLoadBalancer ? '\n⚖️ **Load balancer** distributes traffic across service instances.' : ''}
${stats.hasCdn ? '\n🌐 **CDN** accelerates content delivery at the edge.' : ''}

**Architecture Complexity:** ${getComplexityRating(stats)}`;
}

// ─── Section: Flow Walkthrough ────────────────────────────────────────
function generateFlowSection(analysis) {
  const { flowOrder, outgoing, incoming } = analysis;

  let flow = `## System Flow — Request Lifecycle\n\nThe following describes how a typical request travels through this architecture:\n\n`;

  let step = 1;
  const visited = new Set();

  flowOrder.forEach((node) => {
    if (visited.has(node.id)) return;
    visited.add(node.id);

    const label = getNodeLabel(node);
    const targets = (outgoing[node.id] || []).map((id) => {
      const n = analysis.nodes.find((x) => x.id === id);
      return n ? getNodeLabel(n) : id;
    });
    const sources = (incoming[node.id] || []).map((id) => {
      const n = analysis.nodes.find((x) => x.id === id);
      return n ? getNodeLabel(n) : id;
    });

    flow += `**${step}. ${label}** *(${formatNodeType(node.type)})*\n`;
    flow += `${getNodeFlowDescription(node, sources, targets, analysis)}\n\n`;
    step++;
  });

  if (analysis.stats.hasMessaging && analysis.queueNodes.length > 0) {
    flow += `\n### Asynchronous Flow\n\n`;
    analysis.queueNodes.forEach((queue) => {
      const producers = (incoming[queue.id] || []).map((id) => {
        const n = analysis.nodes.find((x) => x.id === id);
        return n ? getNodeLabel(n) : id;
      });
      const consumers = (outgoing[queue.id] || []).map((id) => {
        const n = analysis.nodes.find((x) => x.id === id);
        return n ? getNodeLabel(n) : id;
      });
      const label = getNodeLabel(queue);
      flow += `**${label}** decouples **${producers.join(', ') || 'producers'}** from **${consumers.join(', ') || 'consumers'}**. Messages are processed asynchronously, ensuring upstream services are not blocked.\n\n`;
    });
  }

  return flow;
}

// ─── Section: Component Details ───────────────────────────────────────
function generateComponentDetailsSection(analysis) {
  const { nodes, outgoing, incoming } = analysis;
  let section = `## Component Reference\n\n`;

  nodes.forEach((node) => {
    const label = getNodeLabel(node);
    const outLabels = (outgoing[node.id] || []).map((id) => {
      const n = nodes.find((x) => x.id === id);
      return n ? getNodeLabel(n) : id;
    });
    const inLabels = (incoming[node.id] || []).map((id) => {
      const n = nodes.find((x) => x.id === id);
      return n ? getNodeLabel(n) : id;
    });

    section += `### ${getNodeEmoji(node.type)} ${label}\n\n`;
    section += `| Property | Value |\n|---|---|\n`;
    section += `| **Type** | ${formatNodeType(node.type)} |\n`;
    section += `| **Receives from** | ${inLabels.length ? inLabels.join(', ') : 'Entry point (no upstream)'} |\n`;
    section += `| **Sends to** | ${outLabels.length ? outLabels.join(', ') : 'Terminal node (no downstream)'} |\n`;

    // Show relevant config fields
    const cfg = node.data || {};
    if (cfg.name) section += `| **Name** | ${cfg.name} |\n`;
    if (cfg.type) section += `| **Sub-type** | ${cfg.type} |\n`;
    if (cfg.method) section += `| **Method** | ${cfg.method} |\n`;
    if (cfg.route) section += `| **Route** | ${cfg.route} |\n`;
    if (cfg.authEnabled !== undefined) section += `| **Auth Required** | ${cfg.authEnabled ? 'Yes' : 'No'} |\n`;
    if (cfg.dbName) section += `| **Database Name** | ${cfg.dbName} |\n`;
    if (cfg.fields && cfg.fields.length > 0) section += `| **Fields** | ${cfg.fields.map(f => f.name).join(', ')} |\n`;

    section += `\n**Role:** ${getNodeRoleDescription(node, analysis)}\n\n`;
  });

  return section;
}

// ─── Section: Mermaid Diagram ─────────────────────────────────────────
function generateMermaidDiagram(nodes, edges) {
  let diagram = `## Architecture Diagram\n\n\`\`\`mermaid\nflowchart TD\n`;

  nodes.forEach((node) => {
    const id = sanitizeId(node.id);
    const label = getNodeLabel(node).replace(/"/g, "'");
    const shape = getMermaidShape(node.type);
    diagram += `    ${id}${shape.open}"${label}"${shape.close}\n`;
  });

  diagram += '\n';

  edges.forEach((edge) => {
    const src = sanitizeId(edge.source);
    const tgt = sanitizeId(edge.target);
    const lbl = edge.label ? `|"${String(edge.label).replace(/"/g, "'")}"| ` : '';
    diagram += `    ${src} -->${lbl}${tgt}\n`;
  });

  diagram += '\n';

  // Classify nodes for styling
  const classMap = {
    apiNode: 'gateway', authNode: 'gateway',
    dbNode: 'data', cacheNode: 'data', storageNode: 'data', replicaNode: 'data',
    queueNode: 'messaging', mailNode: 'messaging', webhookNode: 'messaging',
    loadBalancerNode: 'infra', cdnNode: 'infra', cronNode: 'infra', counterServiceNode: 'infra',
    entityNode: 'application', logicNode: 'application', middlewareNode: 'application',
  };

  const byClass = {};
  nodes.forEach((node) => {
    const cls = classMap[node.type] || 'application';
    if (!byClass[cls]) byClass[cls] = [];
    byClass[cls].push(sanitizeId(node.id));
  });

  Object.entries(byClass).forEach(([cls, ids]) => {
    diagram += `    class ${ids.join(',')} ${cls}\n`;
  });

  diagram += `    classDef gateway fill:#7c3aed,stroke:#6d28d9,color:#fff\n`;
  diagram += `    classDef application fill:#1d4ed8,stroke:#1e40af,color:#fff\n`;
  diagram += `    classDef data fill:#065f46,stroke:#047857,color:#fff\n`;
  diagram += `    classDef messaging fill:#92400e,stroke:#78350f,color:#fff\n`;
  diagram += `    classDef infra fill:#374151,stroke:#1f2937,color:#fff\n`;
  diagram += '```';

  return diagram;
}

// ─── Section: Failure Modes ───────────────────────────────────────────
function generateFailureModesSection(analysis) {
  const { nodes, stats } = analysis;

  let section = `## Failure Modes & Resilience\n\n`;

  const spofs = nodes.filter((n) => {
    const out = (analysis.outgoing[n.id] || []).length;
    const inc = (analysis.incoming[n.id] || []).length;
    return inc + out > 3;
  });

  if (spofs.length > 0) {
    section += `### ⚠️ Potential Single Points of Failure\n\n`;
    spofs.forEach((n) => {
      section += `- **${getNodeLabel(n)}**: High-connectivity node (${(analysis.incoming[n.id] || []).length} in, ${(analysis.outgoing[n.id] || []).length} out). Failure here impacts multiple downstream components.\n`;
    });
    section += '\n';
  }

  section += `### Recommended Resilience Patterns\n\n`;
  if (stats.dbCount > 0) section += `- **Database**: Use replica sets / read replicas. Enable connection pooling.\n`;
  if (stats.hasCaching) section += `- **Cache**: Use cache-aside pattern. Set TTL and invalidation strategy.\n`;
  if (stats.hasMessaging) section += `- **Queue**: Implement dead-letter queues and retry limits.\n`;
  if (stats.apiCount > 1) section += `- **APIs**: Circuit breakers between services. Exponential backoff on retries.\n`;
  if (stats.hasAuth) section += `- **Auth**: Rotate JWT secrets regularly. Implement token refresh flow.\n`;
  section += `- **General**: Add \`/health\` endpoints on all services. Implement graceful shutdown.\n`;

  return section;
}

// ─── Section: Scalability ─────────────────────────────────────────────
function generateScalabilitySection(analysis) {
  const { stats } = analysis;

  let section = `## Scalability Analysis\n\n`;
  section += `### Current Scale Estimate\n\nThis architecture is suitable for **${getScaleEstimate(stats)}**.\n\n`;

  section += `### Bottlenecks to Watch\n\n`;
  if (stats.dbCount === 1 && stats.apiCount > 2) {
    section += `- **Single database** serving ${stats.apiCount} API endpoints — consider read replicas as load grows.\n`;
  }
  if (!stats.hasCaching) {
    section += `- **No caching layer** — high-frequency reads will hit the database directly. Add Redis.\n`;
  }
  if (!stats.hasMessaging && stats.apiCount > 3) {
    section += `- **Synchronous API calls** — consider a message queue to decouple heavy operations.\n`;
  }
  if (!stats.hasLoadBalancer && stats.apiCount > 1) {
    section += `- **No load balancer** — add one to distribute traffic and enable horizontal scaling.\n`;
  }

  section += `\n### Scaling Recommendations\n\n`;
  section += `- Stateless API nodes can be horizontally scaled behind a load balancer.\n`;
  section += `- Databases typically need vertical scaling first, then sharding or read replicas.\n`;
  section += `- Add a CDN layer for static assets and cacheable API responses.\n`;
  section += `- Use \`docker-compose\` or Kubernetes for orchestration at scale.\n`;

  return section;
}

// ─── Section: Tech Stack ──────────────────────────────────────────────
function generateTechStackSection(analysis) {
  const { stats, dbNodes, cacheNodes, queueNodes } = analysis;

  let section = `## Tech Stack\n\n| Layer | Technology |\n|---|---|\n`;
  section += `| Runtime | Node.js (Express.js) |\n`;
  if (dbNodes.length > 0) {
    dbNodes.forEach((n) => {
      const t = n.data?.type || 'mongodb';
      section += `| Database | ${t === 'postgresql' ? 'PostgreSQL' : 'MongoDB'} |\n`;
    });
  }
  if (cacheNodes.length > 0) section += `| Cache | Redis |\n`;
  if (queueNodes.length > 0) section += `| Messaging | RabbitMQ / Queue |\n`;
  if (stats.hasAuth) section += `| Auth | JWT + bcrypt |\n`;
  if (stats.hasMailer) section += `| Email | Nodemailer / SMTP |\n`;
  if (stats.hasStorage) section += `| Storage | S3-compatible Object Storage |\n`;
  section += `| Containerization | Docker + Docker Compose |\n`;

  return section;
}

// ─── Section: Deployment ──────────────────────────────────────────────
function generateDeploymentSection(analysis) {
  const { stats } = analysis;

  return `## Deployment Guide

### Prerequisites
- Node.js 18+, Docker, Docker Compose

### Quick Start

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Configure environment
cp .env.example .env
# Edit .env with your values

# 3. Start infrastructure
docker-compose up -d${stats.dbCount > 0 ? ' # Starts database' : ''}${stats.hasCaching ? ', Redis' : ''}${stats.hasMessaging ? ', Queue' : ''}

# 4. Run the server
npm run dev
\`\`\`

### Production Checklist

- [ ] Set \`NODE_ENV=production\`
${stats.hasAuth ? '- [ ] Rotate \`JWT_SECRET\` to a strong random value\n' : ''}- [ ] Enable HTTPS / TLS termination at reverse proxy (nginx/Caddy)
- [ ] Configure \`CORS_ORIGIN\` to your domain
- [ ] Set up database backups and monitoring
- [ ] Configure log aggregation (e.g. Datadog, Logtail)`;
}

// ─── Helper Functions ─────────────────────────────────────────────────
function getNodeLabel(node) {
  return node.data?.label || node.data?.name || formatNodeType(node.type);
}

function sanitizeId(id) {
  return String(id).replace(/[^a-zA-Z0-9_]/g, '_');
}

function getComplexityRating(stats) {
  if (stats.totalNodes <= 3) return '🟢 Simple (MVP / prototype)';
  if (stats.totalNodes <= 8) return '🟡 Moderate (early-stage production)';
  if (stats.totalNodes <= 15) return '🟠 Complex (requires careful orchestration)';
  return '🔴 Enterprise-scale (requires DevOps expertise)';
}

function getScaleEstimate(stats) {
  if (stats.totalNodes <= 3) return 'small teams and prototypes (~100 concurrent users)';
  if (stats.totalNodes <= 8) return 'early-stage products (~1,000 concurrent users)';
  return 'mid-scale production (~10,000+ concurrent users with proper infrastructure)';
}

function getMermaidShape(nodeType) {
  const shapes = {
    apiNode: { open: '[/', close: '/]' },
    authNode: { open: '[/', close: '/]' },
    loadBalancerNode: { open: '[(', close: ')]' },
    dbNode: { open: '[(', close: ')]' },
    cacheNode: { open: '((', close: '))' },
    queueNode: { open: '[/', close: '/]' },
    entityNode: { open: '[', close: ']' },
    logicNode: { open: '{', close: '}' },
  };
  return shapes[nodeType] || { open: '[', close: ']' };
}

function getNodeEmoji(type) {
  const map = {
    apiNode: '🔀', authNode: '🔐', entityNode: '📋',
    dbNode: '🗄️', cacheNode: '⚡', storageNode: '🪣',
    queueNode: '📨', mailNode: '📧', logicNode: '🧠',
    middlewareNode: '🔧', cronNode: '⏱️', webhookNode: '🔗',
    loadBalancerNode: '⚖️', cdnNode: '🌐', replicaNode: '📑',
    counterServiceNode: '🔢',
  };
  return map[type] || '📦';
}

function formatNodeType(type) {
  const map = {
    apiNode: 'API Endpoint', authNode: 'Auth Service', entityNode: 'Data Entity',
    dbNode: 'Database', cacheNode: 'Cache (Redis)', storageNode: 'Object Storage',
    queueNode: 'Message Queue', mailNode: 'Mail Service', logicNode: 'Business Logic',
    middlewareNode: 'Middleware', cronNode: 'Cron Job', webhookNode: 'Webhook',
    loadBalancerNode: 'Load Balancer', cdnNode: 'CDN', replicaNode: 'Replica',
    counterServiceNode: 'Counter Service',
  };
  return map[type] || (type ? type.replace(/Node$/, '').replace(/([A-Z])/g, ' $1').trim() : 'Component');
}

function getNodeFlowDescription(node, sources, targets, analysis) {
  const label = getNodeLabel(node);
  const srcStr = sources.length ? `from **${sources.join(', ')}**` : 'as an entry point';
  const tgtStr = targets.length ? `forwards to **${targets.join(', ')}**` : 'and terminates (no downstream)';

  const descriptions = {
    apiNode: `Receives HTTP requests ${srcStr}. Validates input, applies middleware, and ${tgtStr}.${node.data?.authEnabled ? ' Requires authentication.' : ''}`,
    authNode: `Handles authentication ${srcStr}. Issues/validates JWT tokens and ${tgtStr}.`,
    entityNode: `Defines the **${label}** data model ${srcStr}. Schema drives generated routes, controllers, and models. ${tgtStr}.`,
    dbNode: `Persists data ${srcStr}. ${node.data?.type === 'postgresql' ? 'Uses PostgreSQL with relational schema.' : 'Uses MongoDB with flexible document schema.'} ${tgtStr}.`,
    cacheNode: `Intercepts repeated queries ${srcStr}. Serves cached responses to reduce database load. ${tgtStr}.`,
    queueNode: `Buffers messages ${srcStr} for asynchronous processing. Decouples producers from consumers. ${tgtStr}.`,
    logicNode: `Executes business logic ${srcStr}. Applies transformation, validation, or computation. ${tgtStr}.`,
    middlewareNode: `Intercepts requests ${srcStr}. Applies cross-cutting concerns (logging, rate limiting, etc.). ${tgtStr}.`,
    mailNode: `Sends transactional emails triggered ${srcStr}. ${tgtStr}.`,
    storageNode: `Handles file upload/retrieval ${srcStr}. Stores objects in S3-compatible storage. ${tgtStr}.`,
    cronNode: `Runs scheduled tasks on a defined interval. Not triggered by requests — operates independently. ${tgtStr}.`,
    webhookNode: `Receives external event callbacks ${srcStr}. Validates payload and ${tgtStr}.`,
    loadBalancerNode: `Distributes incoming traffic ${srcStr} across multiple backend instances. ${tgtStr}.`,
    cdnNode: `Caches and serves static assets or API responses at the edge ${srcStr}. Reduces latency for geographically distributed users. ${tgtStr}.`,
    replicaNode: `Provides a read replica ${srcStr}. Offloads read queries from the primary database. ${tgtStr}.`,
    counterServiceNode: `Maintains atomic counters or rate-limit state ${srcStr}. ${tgtStr}.`,
  };

  return descriptions[node.type] || `Acts as a **${formatNodeType(node.type)}** component ${srcStr}. ${tgtStr}.`;
}

function getNodeRoleDescription(node, analysis) {
  const inCount = (analysis.incoming[node.id] || []).length;
  const outCount = (analysis.outgoing[node.id] || []).length;
  const isEntry = inCount === 0;
  const isTerminal = outCount === 0;

  if (isEntry && isTerminal) return `Standalone component — no upstream or downstream connections.`;
  if (isEntry) return `**Entry point** — initiates the data flow for this architecture.`;
  if (isTerminal) return `**Terminal node** — final destination for data in this flow.`;
  if (inCount + outCount > 4) return `**Hub node** — central to the architecture with high connectivity. Critical for reliability.`;
  return `Intermediary component bridging upstream and downstream layers.`;
}

function getEmptyDocPlaceholder() {
  return `# Architecture Documentation

> Add nodes to your canvas to generate rich documentation automatically.

## What you'll get

- 📖 Full narrative flow walkthrough
- 📊 Auto-generated Mermaid diagram
- 🔧 Component reference with upstream/downstream mapping
- ⚠️ Failure mode analysis
- 📈 Scalability recommendations
- 🚀 Deployment guide`;
}
